# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
# add_newline = false

# Replace the "‚ùØ" symbol in the prompt with "‚ûú"
# [character] # The name of the module we are configuring is "character"
# success_symbol = "[‚ûú](bold green)" # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"

# ~/.config/starship.toml
[character]
error_symbol = 'ü¶π: you got no power here!'

[battery]
unknown_symbol = 'Û∞ÇÑ not charging üòå '  # not_charging_symbol!
charging_symbol = 'Û±ä§ '
# discharging_symbol = 'Û∞ÇÉÛ∞Ä¶ '
discharging_symbol = 'üîãü•µüí¶üö® Discharging '

[[battery.display]]
threshold = 70
style = 'bold red'

[[battery.display]]
threshold = 80
style = 'green'

# [[battery.display]]
# threshold = 50
# style = 'bold red'
# charging_symbol = 'Û±ä§ '
#
# [[battery.display]]
# threshold = 60
# style = 'red'
# charging_symbol = 'Û±ä§ '
#
# [[battery.display]]
# threshold = 70
# style = 'yellow'
# charging_symbol = 'Û±ä• '
#
# # add new state for not charging
# [[battery.display]]
# threshold = 80
# style = 'green'
# charging_symbol = 'Û±ä¶ '

# [[battery.display]]
# threshold = 99
# style = 'green'
# charging_symbol = 'Û±ä¶ '
#
# [[battery.display]]
# threshold = 100
# style = 'bold green'
# charging_symbol = 'Û∞ÇÖ'

[package]
symbol = "Ô£ñ "

[golang]
symbol = "Óòß "
# symbol = "Ô≥ë "
# symbol = "Óò¶ "
# symbol = "Óú§ "

# # Nerd Font Symbols Preset
# [aws]
# symbol = "ÓåΩ  "
#
# [buf]
# symbol = "Ôíù "
#
# [c]
# symbol = "Óòû "
#
# [conda]
# symbol = "ÔÑå "
#
# [dart]
# symbol = "Óûò "
#
# [directory]
# read_only = " Ô†Ω"
#
# [docker_context]
# symbol = "Ôåà "
#
# [elixir]
# symbol = "Óâµ "
#
# [elm]
# symbol = "Óò¨ "
#
# [git_branch]
# symbol = "Ôêò "
#
# [golang]
# symbol = "Óòß "
#
# [haskell]
# symbol = "Óù∑ "
#
# [hg_branch]
# symbol = "Ôêò "
#
# [java]
# symbol = "Óâñ "
#
# [julia]
# symbol = "Óò§ "
#
# [lua]
# symbol = "Óò† "
#
# [memory_usage]
# symbol = "Ô°ö "
#
# [meson]
# symbol = "Ô®∂ "
#
# [nim]
# symbol = "Ôö§ "
#
# [nix_shell]
# symbol = "Ôåì "
#
# [nodejs]
# symbol = "Óúò "
#
# [package]
# symbol = "Ô£ñ "
#
# [python]
# symbol = "Óàµ "
#
# [rlang]
# symbol = "Ô≥í "
#
# [ruby]
# symbol = "Óûë "
#
# [rust]
# symbol = "Óû® "
#
# [scala]
# symbol = "Óú∑ "
#
# [spack]
# symbol = "üÖ¢ "
#
# #/ Nerd Font Symbols Preset

# # Bracketed Segments Preset
# [aws]
# format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
#
# [bun]
# format = '\[[$symbol($version)]($style)\]'
#
# [c]
# format = '\[[$symbol($version(-$name))]($style)\]'
#
# [cmake]
# format = '\[[$symbol($version)]($style)\]'
#
# [cmd_duration]
# format = '\[[‚è± $duration]($style)\]'
#
# [cobol]
# format = '\[[$symbol($version)]($style)\]'
#
# [conda]
# format = '\[[$symbol$environment]($style)\]'
#
# [crystal]
# format = '\[[$symbol($version)]($style)\]'
#
# [daml]
# format = '\[[$symbol($version)]($style)\]'
#
# [dart]
# format = '\[[$symbol($version)]($style)\]'
#
# [deno]
# format = '\[[$symbol($version)]($style)\]'
#
# [docker_context]
# format = '\[[$symbol$context]($style)\]'
#
# [dotnet]
# format = '\[[$symbol($version)(üéØ $tfm)]($style)\]'
#
# [elixir]
# format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
#
# [elm]
# format = '\[[$symbol($version)]($style)\]'
#
# [erlang]
# format = '\[[$symbol($version)]($style)\]'
#
# [gcloud]
# format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
#
# [git_branch]
# format = '\[[$symbol$branch]($style)\]'
#
# [git_status]
# format = '([\[$all_status$ahead_behind\]]($style))'
#
# [golang]
# format = '\[[$symbol($version)]($style)\]'
#
# [haskell]
# format = '\[[$symbol($version)]($style)\]'
#
# [helm]
# format = '\[[$symbol($version)]($style)\]'
#
# [hg_branch]
# format = '\[[$symbol$branch]($style)\]'
#
# [java]
# format = '\[[$symbol($version)]($style)\]'
#
# [julia]
# format = '\[[$symbol($version)]($style)\]'
#
# [kotlin]
# format = '\[[$symbol($version)]($style)\]'
#
# [kubernetes]
# format = '\[[$symbol$context( \($namespace\))]($style)\]'
#
# [lua]
# format = '\[[$symbol($version)]($style)\]'
#
# [memory_usage]
# format = '\[$symbol[$ram( | $swap)]($style)\]'
#
# [meson]
# format = '\[[$symbol$project]($style)\]'
#
# [nim]
# format = '\[[$symbol($version)]($style)\]'
#
# [nix_shell]
# format = '\[[$symbol$state( \($name\))]($style)\]'
#
# [nodejs]
# format = '\[[$symbol($version)]($style)\]'
#
# [ocaml]
# format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
#
# [openstack]
# format = '\[[$symbol$cloud(\($project\))]($style)\]'
#
# [package]
# format = '\[[$symbol$version]($style)\]'
#
# [perl]
# format = '\[[$symbol($version)]($style)\]'
#
# [php]
# format = '\[[$symbol($version)]($style)\]'
#
# [pulumi]
# format = '\[[$symbol$stack]($style)\]'
#
# [purescript]
# format = '\[[$symbol($version)]($style)\]'
#
# [python]
# format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
#
# [raku]
# format = '\[[$symbol($version-$vm_version)]($style)\]'
#
# [red]
# format = '\[[$symbol($version)]($style)\]'
#
# [ruby]
# format = '\[[$symbol($version)]($style)\]'
#
# [rust]
# format = '\[[$symbol($version)]($style)\]'
#
# [scala]
# format = '\[[$symbol($version)]($style)\]'
#
# [spack]
# format = '\[[$symbol$environment]($style)\]'
#
# [sudo]
# format = '\[[as $symbol]\]'
#
# [swift]
# format = '\[[$symbol($version)]($style)\]'
#
# [terraform]
# format = '\[[$symbol$workspace]($style)\]'
#
# [time]
# format = '\[[$time]($style)\]'
#
# [username]
# format = '\[[$user]($style)\]'
#
# [vagrant]
# format = '\[[$symbol($version)]($style)\]'
#
# [vlang]
# format = '\[[$symbol($version)]($style)\]'
#
# [zig]
# format = '\[[$symbol($version)]($style)\]'
#
# #/ Bracketed Segments Preset

# # No Runtime Versions Preset
# [bun]
# format = "via [$symbol]($style)"
#
# [buf]
# format = "via [$symbol]($style)"
#
# [cmake]
# format = "via [$symbol]($style)"
#
# [cobol]
# format = "via [$symbol]($style)"
#
# [crystal]
# format = "via [$symbol]($style)"
#
# [daml]
# format = "via [$symbol]($style)"
#
# [dart]
# format = "via [$symbol]($style)"
#
# [deno]
# format = "via [$symbol]($style)"
#
# [dotnet]
# format = "[$symbol(üéØ $tfm )]($style)"
#
# [elixir]
# format = 'via [$symbol]($style)'
#
# [elm]
# format = 'via [$symbol]($style)'
#
# [erlang]
# format = 'via [$symbol]($style)'
#
# [golang]
# format = 'via [$symbol]($style)'
#
# [helm]
# format = 'via [$symbol]($style)'
#
# [julia]
# format = 'via [$symbol]($style)'
#
# [kotlin]
# format = 'via [$symbol]($style)'
#
# [lua]
# format = 'via [$symbol]($style)'
#
# [meson]
# format = 'via [$symbol]($style)'
#
# [nim]
# format = 'via [$symbol]($style)'
#
# [nodejs]
# format = 'via [$symbol]($style)'
#
# [ocaml]
# format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'
#
# [perl]
# format = 'via [$symbol]($style)'
#
# [php]
# format = 'via [$symbol]($style)'
#
# [pulumi]
# format = 'via [$symbol$stack]($style)'
#
# [purescript]
# format = 'via [$symbol]($style)'
#
# [python]
# format = 'via [$symbol]($style)'
#
# [raku]
# format = 'via [$symbol]($style)'
#
# [red]
# format = 'via [$symbol]($style)'
#
# [rlang]
# format = 'via [$symbol]($style)'
#
# [ruby]
# format = 'via [$symbol]($style)'
#
# [rust]
# format = 'via [$symbol]($style)'
#
# [swift]
# format = 'via [$symbol]($style)'
#
# [vagrant]
# format = 'via [$symbol]($style)'
#
# [vlang]
# format = 'via [$symbol]($style)'
#
# [zig]
# format = 'via [$symbol]($style)'
#
# #/ No Runtime Versions Preset

# # Pure Preset
# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $cmd_duration\
# $line_break\
# $python\
# $character"""
#
# [directory]
# style = "blue"
#
# [character]
# success_symbol = "[‚ùØ](purple)"
# error_symbol = "[‚ùØ](red)"
# vimcmd_symbol = "[‚ùÆ](green)"
#
# [git_branch]
# format = "[$branch]($style)"
# style = "bright-black"
#
# [git_status]
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
# style = "cyan"
# conflicted = "‚Äã"
# untracked = "‚Äã"
# modified = "‚Äã"
# staged = "‚Äã"
# renamed = "‚Äã"
# deleted = "‚Äã"
# stashed = "‚â°"
#
# [git_state]
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# style = "bright-black"
#
# [cmd_duration]
# format = "[$duration]($style) "
# style = "yellow"
#
# [python]
# format = "[$virtualenv]($style) "
# style = "bright-black"
#
# #/ Pure Preset


# # Pastel Powerline Preset
# format = """
# [ÓÇ∂](#9A348E)\
# $username\
# [ÓÇ∞](bg:#DA627D fg:#9A348E)\
# $directory\
# [ÓÇ∞](fg:#DA627D bg:#FCA17D)\
# $git_branch\
# $git_status\
# [ÓÇ∞](fg:#FCA17D bg:#86BBD8)\
# $c\
# $elixir\
# $elm\
# $golang\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# [ÓÇ∞](fg:#86BBD8 bg:#06969A)\
# $docker_context\
# [ÓÇ∞](fg:#06969A bg:#33658A)\
# $time\
# [ÓÇ∞ ](fg:#33658A)\
# """
#
# # Disable the blank line at the start of the prompt
# # add_newline = false
#
# # You can also replace your username with a neat symbol like ÔÑ† to save some space
# [username]
# show_always = true
# style_user = "bg:#9A348E"
# style_root = "bg:#9A348E"
# format = '[$user ]($style)'
#
# [directory]
# style = "bg:#DA627D"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "‚Ä¶/"
#
# # Here is how you can shorten some long paths by text replacement
# # similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = "Ôúò "
# "Downloads" = "ÔÄô "
# "Music" = "ÔÄÅ "
# "Pictures" = "ÔÄæ "
# # Keep in mind that the order matters. For example:
# # "Important Documents" = " ÔúòÔÑ™ "
# # will not be replaced, because "Documents" was already substituted before.
# # So either put "Important Documents" before "Documents" or use the substituted version:
# # "Important Ôúò " = " ÔúòÔÑ™ "
#
# [c]
# symbol = "Óòû "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [docker_context]
# symbol = "Ôåà "
# style = "bg:#06969A"
# format = '[ $symbol $context ]($style) $path'
#
# [elixir]
# symbol = "Óâµ "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [elm]
# symbol = "Óò¨ "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [git_branch]
# symbol = "Ôêò"
# style = "bg:#FCA17D"
# format = '[ $symbol $branch ]($style)'
#
# [git_status]
# style = "bg:#FCA17D"
# format = '[$all_status$ahead_behind ]($style)'
#
# [golang]
# symbol = "Óòß "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [haskell]
# symbol = "Óù∑ "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [java]
# symbol = "Óâñ "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [julia]
# symbol = "Óò§ "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [nodejs]
# symbol = "Óúò"
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [nim]
# symbol = "Ôö§ "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [rust]
# symbol = "Óû®"
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [scala]
# symbol = "Óú∑ "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#33658A"
# format = '[ ‚ô• $time ]($style)'
#
# #/ Pastel Powerline Preset
